name: checkov
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: write-all
      security-events: write-all
      actions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
